templateDir: ./sdk-resources/resources
files:
  package.mustache:
    templateType: SupportingFiles
    destinationFilename: package.json
  api_doc.mustache:
    templateType: APIDocs
    destinationFilename: .md
  model_doc.mustache:
    templateType: ModelDocs
    destinationFilename: .md
npmName: sailpoint-sdk
npmRepository: sailpoint.com
npmVersion: 1.3.3
useSingleRequestParameter: true
apiVersion: beta
